# -*- coding: utf-8 -*-
"""pyramid_zeynepduman_elifaskin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9DwrHaevm-c5tFQDMZSSllI3Yhxvk8O
"""

# This game is designed by Zeynep İrem Duman and Elif Aşkın. However, the code was written individually.

import random
def pyramid_zeynepduman_elifaskin():
  print ('WELCOME TO PYRAMID GAME!')
  print ('This game is inspired by the food chain in its design.')
  print ('RULES: We have 3 character. Lion,Elephant and Crocodile. Lion eats crododile.Crocodile eats elephant. Elephant eats lion.Law of nature😜')
  print ("The player who leads  2 points wins the game.Good luck!")
  choices = ["lion", "elephant", "crocodile"]
  user_score = 0
  computer_score = 0
  while True:
        user_choice = input("Lion, Elephant or Crocodile? (If you do not want to play write 'exit'):").lower()
        if user_choice == 'exit':
           print("GAME OVER😡")
           break
        if user_choice not in choices:
            print('Invalid choice. Please try again 😮')
            continue

        #Determine the selection of the camputer.
        computer_choice = random.choice(choices)

        print (f"Your choice: {user_choice}")
        print (f"Camputer's choice: {computer_choice}")


        # Check the game result
        if user_choice == computer_choice:
            print ("Scoreless! Try Again🙂")
        elif (
            (user_choice == 'lion' and computer_choice == 'crocodile') or
            (user_choice == 'elephant' and computer_choice == 'lion') or
            (user_choice == 'crocodile' and computer_choice == 'fil') ):
            print ("Congratulations! You win🥳")
            user_score += 1

            print (f"Skor: You {user_score} - {computer_score} Computer")
        else:
            print ("Sorry! You lose🥹")
            computer_score += 1

            print (f"Skor: You {user_score} - {computer_score} Computer")

        # Check the game. The player who leads 2 points wins the game.
        if abs(user_score - computer_score) ==2 :
            if user_score > computer_score:
                print ("The game is over.Congratulations.You win🥳🥳!")

            else:
                  print("The game is over.Sorry. You lose🥹!")
                  play_again = input("Do you want to play again ? (Yes/No)")
            if play_again.lower() != 'yes':
             print("THE GAME İS OVER.HAVE A NICE DAY")
             break
            else:
             print("New game is starting")
             user_score = 0
             computer_score = 0

pyramid_zeynepduman_elifaskin()

